services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\SchemaPending\:
    resource: '../Classes/*'
    exclude: '../Classes/Model'

  Brotkrueml\SchemaPending\EventListener\RegisterAdditionalProperties:
    tags:
      - name: event.listener
        identifier: 'ext-schema-pending/registerAdditionalProperties'
        event: Brotkrueml\Schema\Event\RegisterAdditionalTypePropertiesEvent
