services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\SchemaPending\:
    resource: '../Classes/*'

  Brotkrueml\SchemaPending\EventListener\RegisterAdditionalProperties:
    tags:
      - name: event.listener
        identifier: 'ext-schema-pending/registerAdditionalProperties'

  Brotkrueml\SchemaPending\EventListener\RegisterRemovedProperties:
    tags:
      - name: event.listener
        identifier: 'ext-schema-pending/registerRemovedProperties'
